image: Visual Studio 2019

version: 1.0.2-CI{build}

clone_depth: 10

#Skip builing if we only modify text files
skip_commits:
  files:
    - '**/*.md'
    - '**/*.html'
    - '**/*.js'

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

# scripts to run before build
before_build:
  dotnet restore Chromium.AspNetCore.Bridge.AppVeyor.sln

build:
  project: Chromium.AspNetCore.Bridge.AppVeyor.sln
  # MSBuild verbosity level
  verbosity: normal

artifacts:
  - path: '**\*.nupkg'
    name: nupkgfiles

# Publish to myget.org feed
deploy:
  provider: NuGet
  server: https://www.myget.org/F/cefsharp/api/v2/package
  api_key:
    secure: XR2LM25h8XW2uAjgQL5o4bUpMVL2NXWF7019HhMiMftP/Ip8UH4pp+hi+OUYMhfE
  skip_symbols: false
  symbol_server: https://www.myget.org/F/cefsharp/api/v2/package
  artifact: nupkgfiles
  on:
      branch: master                # release from master branch only
      APPVEYOR_REPO_TAG: true       # deploy on tag push only
